import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {attachWeather,summarizeWeather} from '../src/weather.mjs';import {weatherMatches} from '../src/weather-match.mjs';import {selectEvents,defaults} from '../src/analysis.mjs';
test('snow reports are explicit; cold and missing descriptions do not imply snow',()=>{assert.equal(weatherMatches({temp:-10,description:''},'Snow reported'),false);assert.equal(weatherMatches({temp:2,description:'Rain,Snow'},'Snow reported'),true);assert.equal(weatherMatches({temp:null},'Below freezing'),false);assert.equal(weatherMatches(null,'Weather unavailable'),true)});
test('UTC-hour join keeps daylight saving transitions and sub-hour events correct',()=>{
 const hours=[{utc:'2025-07-01T07:00:00.000Z',date:'2025-07-01',hour:1,temp:2}];const events=attachWeather([{utc:'2025-07-01T07:59:00Z'},{utc:'2025-07-01T08:00:00Z'}],hours);assert.equal(events[0].weather,hours[0]);assert.equal(events[1].weather,null);
 const data=JSON.parse(fs.readFileSync('public/data/weather.json'));const summer=data.hours.find(h=>h.lst==='2025-07-01 00:00');assert.equal(summer.utc,'2025-07-01T07:00:00.000Z');assert.equal(summer.hour,1);const winter=data.hours.find(h=>h.lst==='2025-01-01 00:00');assert.equal(winter.hour,0);
});
test('weather rates use observation hours with matching dates and periods; category does not reduce hours',()=>{
 const hours=[{utc:'2025-02-01T15:00:00Z',date:'2025-02-01',hour:8,weekend:false,temp:-5,description:'Snow',visibility:2},{utc:'2025-02-01T16:00:00Z',date:'2025-02-01',hour:9,weekend:false,temp:-5,description:'Snow',visibility:2},{utc:'2025-02-01T23:00:00Z',date:'2025-02-01',hour:16,weekend:false,temp:-5,description:'Snow',visibility:2}];
 const events=[{...hours[0],category:'Signals',weather:hours[0]},{...hours[0],category:'Other',weather:hours[0]}];const config={...defaults,period:'Morning peak',category:'Signals',weather:'Snow reported'};const row=summarizeWeather(events,hours,config).find(r=>r.condition==='Snow reported');assert.equal(row.events,1);assert.equal(row.hours,2);assert.equal(row.per100Hours,50);assert.equal(selectEvents(events,config).length,1);
});
test('weather snapshot is unique, full-year and preserves missing observations',()=>{const {hours,audit}=JSON.parse(fs.readFileSync('public/data/weather.json'));assert.ok(hours.length>32000);assert.equal(new Set(hours.map(h=>h.utc)).size,hours.length);assert.equal(hours.filter(h=>h.utc.startsWith("2024")).length,8784);assert.equal(hours.filter(h=>h.temp===null).length,audit.tempMissing);assert.ok(hours.every(h=>h.temp===null||Number.isFinite(h.temp)));});
