import {useEffect,useState} from 'react';
import {loadSnapshot} from './domain/loadSnapshot';
import {readReviews} from './InspectionReview';
export function AgentPage(){
 const [snapshot,setSnapshot]=useState<any>(null),[cutoff,setCutoff]=useState('future'),[location,setLocation]=useState('all'),[question,setQuestion]=useState(''),[messages,setMessages]=useState<{role:string;content:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();loadSnapshot('/data/forecast-eb30.json.gz',c.signal).then(setSnapshot).catch(()=>{if(!c.signal.aborted)setError('Could not load forecast evidence.')});return()=>c.abort()},[]);
 const forecast=snapshot?.forecasts.find((f:any)=>cutoff==='future'?f.mode==='future':f.cutoff===cutoff);
 async function ask(text=question){if(!text.trim()||busy||!forecast)return;setBusy(true);setError('');const next=[...messages,{role:'user',content:text}].slice(-19);setMessages(next);setQuestion('');const rows=location==='all'?forecast.rows.slice(0,20):forecast.rows.filter((r:any)=>r.id===location);const reviewKey=`calgary-eb-review:${snapshot.dataFingerprint}:${forecast.mode}:${forecast.cutoff}:${forecast.end}`;const reviews=readReviews(reviewKey);
 try{const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next,context:{version:snapshot.version,cutoff:forecast.cutoff,end:forecast.end,mode:forecast.mode,model:'Pure EB, fixed three-year pooled history',caveats:snapshot.caveats,evaluation:forecast.evaluation,rows:rows.map((row:any)=>({...row,review:reviews[row.id]??null}))}})});const v=await r.json();if(!r.ok)throw Error(v.error||'Agent request failed');setMessages([...next,{role:'assistant',content:v.answer}])}catch(e){setError(e instanceof Error?e.message:'Agent request failed')}finally{setBusy(false)}}
 return <div className="decision-panel agent-page"><div className="decision-heading"><h2>Evidence Agent</h2><span>CONVERSATION / MONTHLY OUTLOOK</span></div><p>Ask about the monthly EB shortlist, source reports, mapped facilities and saved reviews. Answers use the evidence selected below; this assistant cannot verify field conditions or execute actions.</p><p className="notice">Your questions and selected evidence are sent to the configured model provider when you send a message. API credentials stay on the server.</p><div className="forecast-controls"><label>Evidence window<select aria-label="Agent evidence window" disabled={busy} value={cutoff} onChange={e=>{setCutoff(e.target.value);setLocation('all');setMessages([])}}><option value="future">Latest future forecast</option>{snapshot?.forecasts.filter((f:any)=>f.mode==='backtest').map((f:any)=><option key={f.cutoff}>{f.cutoff}</option>)}</select></label><label>Location<select aria-label="Agent location" disabled={busy} value={location} onChange={e=>{setLocation(e.target.value);setMessages([])}}><option value="all">Model Top20</option>{forecast?.rows.slice(0,20).map((r:any)=><option value={r.id} key={r.id}>{r.rank}. {r.name}</option>)}</select></label><button disabled={busy} onClick={()=>{setMessages([]);setError('')}}>Clear conversation</button></div><p>Evidence: {forecast?`${forecast.cutoff} ~ ${forecast.end} · ${forecast.mode}`:'Loading…'}. Conversation resets when the evidence selection changes.</p><div className="outlook-tags">{['Explain this shortlist and its uncertainty','What should we inspect at these locations?','How does EB compare with the baseline?'].map(q=><button key={q} disabled={busy||!forecast} onClick={()=>ask(q)}>{q}</button>)}</div><div className="agent-messages" aria-label="Agent conversation" aria-live="polite">{messages.length===0&&<p>Choose a location or ask about the Top20 to start.</p>}{messages.map((m,i)=><article key={i} className={'agent-message '+m.role}><strong>{m.role==='user'?'You':'Evidence Agent'}</strong><p>{m.content}</p></article>)}{busy&&<p role="status">Reading selected evidence…</p>}</div>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();ask()}}><label>Question<textarea aria-label="Agent question" value={question} maxLength={6000} disabled={busy} onChange={e=>setQuestion(e.target.value)} placeholder="Why is this location prioritized?"/></label><button disabled={busy||!forecast||!question.trim()}>{busy?'Responding…':'Send question'}</button></form></div>
}
