import { useEffect, useState } from "react";
import { loadSnapshot } from "./domain/loadSnapshot";
import { downloadJson } from "./domain/download";
import { ForecastMap } from "./components/ForecastMap";
interface Row { id:string; name:string; kind:string; lon:number; lat:number; predicted:number; baseline:number; count:number; historyReports:number; priorWeight:number; low90:number; high90:number; target:number|null; reportEvidence:{id:string; date:string; description:string}[] }
interface Metrics { top20:number; top100:number; deviance:number; expected:number; observed:number; activeSiteMAE:number }
interface Forecast { cutoff:string; end:string; mode:string; historyStart:string; rows:Row[]; expectedTotal:number; evaluation:{eb:Metrics; rate:Metrics}|null }
interface Snapshot { version:string; dataThrough:string; units:number; selection:string; caveats:string[]; forecasts:Forecast[] }
export function EBForecastPanel({onSeven}:{onSeven:()=>void}) {
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(""),[mode,setMode]=useState("backtest"),[cutoff,setCutoff]=useState("2026-06-30"),[result,setResult]=useState<Forecast|null>(null),[revealed,setRevealed]=useState(false),[selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{const c=new AbortController();loadSnapshot('/data/forecast-eb30.json.gz',c.signal).then(v=>{const d=v as Snapshot;if(!Array.isArray(d?.forecasts)||d.forecasts.some(f=>!Array.isArray(f.rows)))throw Error('Invalid EB snapshot');setData(d)}).catch(e=>{if(!c.signal.aborted)setError(String(e))});return()=>c.abort()},[]);
 const current=data?.forecasts.find(f=>f.mode===mode&&(mode==='future'||f.cutoff===cutoff));
 const stale=result!==null&&result!==current;
 const focus=result?.rows.find(r=>r.id===selected);
 return <div className="decision-panel">
 <div className="decision-heading"><h2>Forward outlook</h2><span>EXPERIMENTAL / PURE EMPIRICAL BAYES</span></div>
 <p className="notice">Next 30 days uses precomputed pure EB on the full road/intersection inventory. Three-year history blends each site's reports with a site-characteristic prior. These units differ from historical dashboard locations. All report types are pooled; weather, time and learned type weights do not apply.</p>
 <div className="forecast-modes" role="group" aria-label="Forecast mode"><button aria-pressed={mode==='backtest'} onClick={()=>{setMode('backtest');setRevealed(false)}}>Historical backtest</button><button aria-pressed={mode==='future'} onClick={()=>{setMode('future');setRevealed(false)}}>Future forecast</button></div>
 <div className="forecast-controls"><label>Historical cutoff<select aria-label="EB cutoff" disabled={mode==='future'||!data} value={cutoff} onChange={e=>{setCutoff(e.target.value);setRevealed(false)}}>{data?.forecasts.filter(f=>f.mode==='backtest').map(f=><option key={f.cutoff}>{f.cutoff}</option>)}</select></label><label>Forecast window<select aria-label="Forecast horizon" value={30} onChange={()=>onSeven()}><option value={7}>Next 7 days</option><option value={30}>Next 30 days</option></select></label><button disabled={!current} onClick={()=>{setResult(current!);setRevealed(false);setSelected(null)}}>Generate forecast</button></div>
 <p>Backtests are available at six precomputed cutoffs. Future outlook uses the latest complete local date: {data?.dataThrough??'loading…'}. Refresh requires the offline pipeline.</p>
 {error&&<p role="alert">{error}</p>}{stale&&<p className="notice">Settings changed. Generate a new forecast.</p>}
 {result&&!stale&&<><button onClick={()=>downloadJson({version:data!.version,model:'Pure EB',horizonDays:30,units:data!.units,selection:data!.selection,caveats:data!.caveats,forecast:result},'calgary-eb30-forecast.json')}>Export forecast report</button><p>Forecast period: day after {result.cutoff} through {result.end}. Fitted history: {result.historyStart} ~ {result.cutoff}. Expected reports across {data!.units.toLocaleString()} units: {result.expectedTotal.toFixed(1)}.</p>
 <ForecastMap result={{...result,objective:'all',historyLabel:'past 90 days',top:result.rows.slice(0,20)}}/>
 <table><thead><tr><th>Location</th><th>Past 90 days</th><th>Expected reports</th><th>90% predictive interval</th><th>Rate baseline</th><th>Own-history / prior</th>{revealed&&<th>Actual reports</th>}</tr></thead><tbody>{result.rows.slice(0,20).map(r=><tr key={r.id}><td><button onClick={()=>setSelected(r.id)}>{r.name}</button><small>{r.kind} · {r.id}</small></td><td>{r.count}</td><td>{r.predicted.toFixed(2)}</td><td>{r.low90} ~ {r.high90}</td><td>{r.baseline.toFixed(2)}</td><td>{Math.round((1-r.priorWeight)*100)}% / {Math.round(r.priorWeight*100)}%</td>{revealed&&<td>{r.target}</td>}</tr>)}</tbody></table>
 {focus&&<section><h3>{focus.name} · EB-unit evidence</h3><p>{focus.historyReports} reports in fitted history. Source samples belong to this EB unit, not the reactive grouping.</p>{focus.reportEvidence.map(e=><article key={e.id}><strong>{e.date}</strong><p>{e.description}</p><small>Source ID: {e.id}</small></article>)}</section>}
 {result.evaluation?<><button onClick={()=>setRevealed(v=>!v)}>{revealed?'Hide later outcomes':'Reveal what happened next'}</button>{revealed&&<div className="notice"><p>Later reports: {result.evaluation.eb.observed}. Model Top 20 coverage: {result.evaluation.eb.top20}; rate-baseline Top 20: {result.evaluation.rate.top20}. Top100: {result.evaluation.eb.top100} vs {result.evaluation.rate.top100}.</p><p>Poisson deviance: {result.evaluation.eb.deviance.toFixed(4)} vs baseline {result.evaluation.rate.deviance.toFixed(4)}. Active-site MAE: {result.evaluation.eb.activeSiteMAE.toFixed(3)} vs {result.evaluation.rate.activeSiteMAE.toFixed(3)}.</p></div>}</>:<p>Future outcomes are unavailable; no accuracy or coverage is calculated.</p>}
 </>}
 <details><summary>Model and validation details</summary><p>Pure EB = w × SPF + (1 − w) × own-history count, scaled by 30 / history days; w = k / (k + SPF). Poisson SPF uses road characteristics and partial traffic-volume observations; negative-binomial posterior gives predictive intervals. History is fixed at three years.</p><p>Six exploratory 2026 windows favour EB on average for Top20/Top100 and deviance, but not every window or active-site error. This does not establish operational safety or validate event-type weights. The seven-day forecast retains Ridge Poisson.</p>{data?.caveats.map(c=><p key={c}>{c}</p>)}</details>
 </div>;
}
