import { InspectionReview, SiteAssets, readReviews, type InspectionRecords } from "./InspectionReview";
import { suggestImprovement, type SiteControl } from "./domain/countermeasures";
import { useEffect, useState, useMemo } from "react";
import { loadSnapshot } from "./domain/loadSnapshot";
import { downloadJson } from "./domain/download";
import { ForecastMap } from "./components/ForecastMap";
interface Row { siteControl?:SiteControl; rank:number; id:string; name:string; kind:string; lon:number; lat:number; predicted:number; baseline:number; count:number; historyReports:number; priorWeight:number; low90:number; high90:number; target:number|null; reportEvidence:{id:string; date:string; description:string}[] }
interface Metrics { top20:number; top100:number; deviance:number; expected:number; observed:number; activeSiteMAE:number }
interface Forecast { cutoff:string; end:string; mode:string; historyStart:string; rows:Row[]; expectedTotal:number; evaluation:{eb:Metrics; rate:Metrics}|null }
interface Snapshot { dataFingerprint:string; version:string; dataThrough:string; units:number; selection:string; caveats:string[]; forecasts:Forecast[] }
export function EBForecastPanel({onSeven}:{onSeven:()=>void}) {
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(""),[mode,setMode]=useState("backtest"),[cutoff,setCutoff]=useState("2026-06-30"),[result,setResult]=useState<Forecast|null>(null),[revealed,setRevealed]=useState(false),[selected,setSelected]=useState<string|null>(null),[retry,setRetry]=useState(0),[reviews,setReviews]=useState<InspectionRecords>({}),[reviewFilter,setReviewFilter]=useState("All locations");
 useEffect(()=>{setError('');const c=new AbortController();loadSnapshot('/data/forecast-eb30.json.gz',c.signal).then(v=>{const d=v as Snapshot;if(!Array.isArray(d?.forecasts)||d.forecasts.some(f=>!Array.isArray(f.rows)))throw Error('Invalid EB snapshot');setData(d)}).catch(e=>{if(!c.signal.aborted)setError(String(e))});return()=>c.abort()},[retry]);
 const current=data?.forecasts.find(f=>f.mode===mode&&(mode==='future'||f.cutoff===cutoff));
 const stale=result!==null&&result!==current;
 const reviewKey = data&&result ? `calgary-eb-review:${data.dataFingerprint}:${result.mode}:${result.cutoff}:${result.end}` : '';
 useEffect(()=>{setReviews(reviewKey?readReviews(reviewKey):{})},[reviewKey]);
 function saveReview(id:string,record:import('./InspectionReview').InspectionRecord) {const next={...reviews,[id]:record};try {localStorage.setItem(reviewKey,JSON.stringify(next));setReviews(next);return true}catch{return false}}
 const preview=useMemo(()=>result?{...result,objective:'all' as const,historyLabel:'past 90 days',top:result.rows.slice(0,20)}:null,[result]);
 const shortlist=result?.rows.slice(0,20)??[];
 const filtered=shortlist.filter(r=>reviewFilter==='All locations'||(reviewFilter==='Not reviewed'?!reviews[r.id]:reviews[r.id]?.status===reviewFilter));
 const focus=result?.rows.find(r=>r.id===selected);
 return <div className="decision-panel">
 <div className="decision-heading"><h2>Forward outlook</h2><span>EXPERIMENTAL / PURE EMPIRICAL BAYES</span></div>
 <div className="outlook-intro"><span className="outlook-eyebrow">LOOK AHEAD / 30 DAYS</span><h3>Where should analysts look next?</h3><p>Review 20 locations with the highest expected traffic-report activity. Open the map, inspect source evidence, then replay a past window to compare with a simple recent-history baseline.</p><div className="outlook-tags"><span>Pure empirical Bayes</span><span>All report types · all hours</span><span>Experimental priorities</span></div></div>
 <section className="algorithm-note" aria-label="Algorithm and rationale"><span className="outlook-eyebrow">ALGORITHM / WHY THIS MODEL</span><h3>Pure Empirical Bayes · next 30 days</h3><p>Combines three years of a location’s own report history with an expected count from similar road or intersection characteristics. Quiet locations lean more on similar sites; locations with substantial history lean more on their own records.</p><p><strong>Why EB:</strong> on the same road/intersection units across six exploratory 2026 windows, average Top20 capture was 36.8 reports versus 33.0 for recent frequency and 32.8 for temporal Poisson. EB also had the best average Top100 capture and lowest count deviance. This supports the monthly prototype choice, not uniform superiority: some windows and active-site errors favour the baseline.</p><p>Three-year history is fixed rather than tuned. All report types are pooled; forecasts estimate report activity, not crash probability or severity.</p></section>
 <div className="forecast-modes" role="group" aria-label="Forecast mode"><button aria-pressed={mode==='backtest'} onClick={()=>{setMode('backtest');setRevealed(false)}}>Historical backtest</button><button aria-pressed={mode==='future'} onClick={()=>{setMode('future');setRevealed(false)}}>Future forecast</button></div>
 <div className="forecast-controls"><label>{mode==='future'?'Evidence through':'Replay cutoff'}<select aria-label="EB cutoff" disabled={mode==='future'||!data} value={cutoff} onChange={e=>{setCutoff(e.target.value);setRevealed(false)}}>{mode==='future'?<option value={cutoff}>{data?.dataThrough??'Loading…'}</option>:data?.forecasts.filter(f=>f.mode==='backtest').map(f=><option key={f.cutoff}>{f.cutoff}</option>)}</select></label><label>Forecast window<select aria-label="Forecast horizon" value={30} onChange={()=>onSeven()}><option value={7}>Next 7 days</option><option value={30}>Next 30 days</option></select></label><button disabled={!current} onClick={()=>{setResult(current!);setRevealed(false);setSelected(null)}}>Generate forecast</button></div>
 <p className="outlook-context">{mode==='backtest'?'Choose one of six replay dates. Later observations stay hidden until you reveal them.':'The outlook starts after the latest complete day. Later observations are not yet available.'}</p>{!data&&!error&&<p role="status">Loading forecast snapshot…</p>}
 {error&&<div role="alert"><p>Could not load the forecast snapshot. Check your connection and try again.</p><button onClick={()=>setRetry(v=>v+1)}>Retry loading</button></div>}{stale&&<p className="notice">Settings changed. Generate a new forecast.</p>}
 {result&&!stale&&<><button onClick={()=>downloadJson({version:data!.version,model:'Pure EB',horizonDays:30,units:data!.units,selection:data!.selection,caveats:data!.caveats,inspectionReviews:reviews,forecast:result},'calgary-eb30-forecast.json')}>Export forecast report</button><p>Forecast period: day after {result.cutoff} through {result.end}. Fitted history: {result.historyStart} ~ {result.cutoff}. Expected reports across {data!.units.toLocaleString()} units: {result.expectedTotal.toFixed(1)}.</p>
 <div className="outlook-stats"><div><span>Expected at Top 20</span><strong>{result.rows.slice(0,20).reduce((s,r)=>s+r.predicted,0).toFixed(1)}</strong><small>reports over the next 30 days</small></div><div><span>Planning shortlist</span><strong>20</strong><small>locations for analyst review</small></div><div><span>Evidence basis</span><strong>3 years</strong><small>own history + similar-site prior</small></div></div>
 <ForecastMap result={preview!} selectedId={selected} onSelect={setSelected}/>
 <div className="scope-apply-actions"><label>Review status <select aria-label="Review status filter" value={reviewFilter} onChange={e=>setReviewFilter(e.target.value)}>{["All locations","Not reviewed","Worth inspecting","Already addressed","Not applicable","Needs more information"].map(v=><option key={v}>{v}</option>)}</select></label><strong>{shortlist.filter(r=>reviews[r.id]).length} / {shortlist.length} reviewed</strong><button onClick={()=>downloadJson({version:data!.version,dataFingerprint:data!.dataFingerprint,cutoff:result.cutoff,end:result.end,mode:result.mode,filter:reviewFilter,scope:"Filtered model Top20; saved reviews only",locations:filtered.map(r=>({rank:r.rank,id:r.id,name:r.name,lon:r.lon,lat:r.lat,expected:r.predicted,interval90:[r.low90,r.high90],facilities:r.siteControl,review:reviews[r.id]??null}))},"calgary-inspection-shortlist.json")}>Export inspection shortlist</button></div>
 <div className="outlook-table" role="region" aria-label="Thirty-day priority shortlist" tabIndex={0}><table><thead><tr><th>Location</th><th>Review status</th><th>Past 90 days</th><th>Expected reports</th><th>90% predictive interval</th><th>Rate baseline</th><th>Own history / similar sites</th>{revealed&&<th>Actual reports</th>}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><button aria-pressed={selected===r.id} onClick={()=>setSelected(r.id)}><span className="outlook-rank">{r.rank}</span>{r.name}</button><small>{r.kind} · {r.id}</small></td><td><span className="review-status">{reviews[r.id]?.status??"Not reviewed"}</span></td><td>{r.count}</td><td>{r.predicted.toFixed(2)}</td><td>{r.low90} ~ {r.high90}</td><td>{r.baseline.toFixed(2)}</td><td>{Math.round((1-r.priorWeight)*100)}% / {Math.round(r.priorWeight*100)}%</td>{revealed&&<td>{r.target}</td>}</tr>)}</tbody></table></div>{filtered.length===0&&<p role="status">No Top20 locations match this review filter. The map continues to show the full forecast.</p>}
 {focus&&<section className="outlook-evidence" aria-label="Selected location evidence"><span className="outlook-eyebrow">LOCATION / {focus.rank.toString().padStart(2,'0')}</span><h3>{focus.name} · EB-unit evidence</h3><p>{focus.priorWeight>=0.5?'This estimate leans more on similar sites.':'This estimate leans more on this location’s own history.'} A 90% predictive interval describes count uncertainty, not safety confidence.</p><p>{focus.historyReports} reports in fitted history. Source samples belong to this EB unit, not the reactive grouping.</p><SiteAssets control={focus.siteControl}/>{result.mode==='future'&&<CountermeasureNote control={focus.siteControl}/>}
 <InspectionReview key={reviewKey+focus.id} control={focus.siteControl} record={reviews[focus.id]} onSave={r=>saveReview(focus.id,r)}/>
 {focus.reportEvidence.length===0&&<p>No source samples are available for this location in the fitted history.</p>}{focus.reportEvidence.map(e=><article key={e.id}><strong>{e.date}</strong><p>{e.description}</p><small>Source ID: {e.id}</small></article>)}</section>}
 {result.evaluation?<><button onClick={()=>setRevealed(v=>!v)}>{revealed?'Hide later outcomes':'Reveal what happened next'}</button>{revealed&&<div className="notice"><p>Later reports: {result.evaluation.eb.observed}. Model Top 20 coverage: {result.evaluation.eb.top20}; rate-baseline Top 20: {result.evaluation.rate.top20}. Top100: {result.evaluation.eb.top100} vs {result.evaluation.rate.top100}.</p><p>Poisson deviance: {result.evaluation.eb.deviance.toFixed(4)} vs baseline {result.evaluation.rate.deviance.toFixed(4)}. Active-site MAE: {result.evaluation.eb.activeSiteMAE.toFixed(3)} vs {result.evaluation.rate.activeSiteMAE.toFixed(3)}.</p></div>}</>:<p>Future outcomes are unavailable; no accuracy or coverage is calculated.</p>}
 </>}
 <p className="notice">Report hotspots are candidates for review, not crash probabilities or verified danger. EB roads/intersections differ from reactive locations. Weather and event-type weights do not apply.</p><details><summary>Model and validation details</summary><p>Precomputed snapshot; refresh requires the offline pipeline. Current export contains the top 1,000 predictions per cutoff; evaluation covers the full inventory.</p><p>Pure EB = w × SPF + (1 − w) × own-history count, scaled by 30 / history days; w = k / (k + SPF). Poisson SPF uses road characteristics and partial traffic-volume observations; negative-binomial posterior gives predictive intervals. History is fixed at three years.</p><p>Six exploratory 2026 windows favour EB on average for Top20/Top100 and deviance, but not every window or active-site error. This does not establish operational safety or validate event-type weights. The seven-day forecast retains Ridge Poisson.</p>{data?.caveats.map(c=><p key={c}>{c}</p>)}</details>
 </div>;
}

function CountermeasureNote({control}:{control?:SiteControl}) {
 const suggestion=suggestImprovement(control);
 return <section aria-label="Candidate improvement"><h4>Candidate improvement · expert review required</h4>{suggestion?<><p><strong>{suggestion.action}</strong> · {suggestion.current}</p><p>{suggestion.source}</p><a href={'https://cmfclearinghouse.fhwa.dot.gov/detail.php?facid='+({'Review signal warrants':'9144','Signing and visibility improvements':'8927','Assess variable-speed feasibility':'11834'}[suggestion.action]??'')} target="_blank" rel="noreferrer">Open CMF study</a><p>Study CMF: {suggestion.cmf}. This is a crash modification factor from an external study, not a predicted reduction in traffic reports. Verify site geometry, existing equipment, study applicability and engineering warrants before selecting a treatment.</p></>:<p>No supported treatment match. Road class alone does not establish a ramp or justify a ramp meter; local engineering review is needed.</p>}</section>;
}
